# Generated by Django 3.2.8 on 2021-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=85)),
                ('phone', models.CharField(max_length=13)),
                ('Desc', models.CharField(max_length=300)),
            ],
        ),
    ]
